ddqn:
  gamma: 0.99
  learning_rate: 5e-4
  batch_size: 64

  buffer:
    size: 100000
    min_size: 2000

  epsilon:
    start: 1.0
    end: 0.05
    decay_steps: 25000

  target_update:
    tau: 0.005
    frequency: 1000

  training:
    episodes: 500
    steps_per_episode: 50

  optimization:
    grad_clip: 10.0

  network:
    hidden1: 256
    hidden2: 256
    value_hidden: 128
    adv_hidden: 128
