logging:
  tensorboard:
    log_dir: "runs/"
    ddqn_log_dir: "runs/DDQN_training"
    ppo_log_dir: "runs/PPO_training"

  checkpoints:
    save_best: true
    save_last: true
    ddqn_ckpt_dir: "checkpoints/DDQN_training"
    ppo_ckpt_dir: "checkpoints/PPO_training"

evaluation:
  target_quality: 80
  metrics:
    - reward
    - altitude
    - quality

speed_schedule:
  start_speed: 0.6
  delta_speed: 1.8
