yolo:
  model: yolov8m

  dataset:
    name: pobed
    root: "/content/drive/MyDrive/pobed/yolo"

  output:
    trainval_dir: "/content/yolo_aug_trainval"
    runs_dir: "/content/drive/MyDrive/runs"

  training:
    img_size: 1024
    epochs: 200
    batch: 4
    patience: 30

  augmentation:
    max_aug_per_source: 10

    targets:
      train_egg_images: 650
      train_larvae_images: 650
      val_egg_images: 80
      val_non_egg: 2000

  classes:
    names: ["larvae", "adult_beetle", "egg_cluster"]
    larvae_id: 0
    egg_id: 2

  seed: 0
